In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\dhrub\Desktop\Dengue_summary_report\Kaski_Dengue_cases.csv")

In [3]:
df

,S.N,Disease,Sex,Age,Date of Registration (M/d/yyyy),Responsible province,Responsible ward no,Responsible district,Responsible municipality,Reporting user,Creation date (M/d/yyyy)
0,1,Dengue,Female,56,9/18/2025,Gandaki,10.0,Kaski,NaN,Regional1 hos,9/19/2025
1,2,Dengue,Female,75,9/10/2025,Gandaki,8.0,Kaski,Pokhara Metropolitan City,Metrocity1 hos,9/16/2025
2,3,Dengue,Female,43,9/13/2025,Gandaki,NaN,Kaski,Pokhara Metropolitan City,Regional1 hos,9/14/2025
3,4,Dengue,Female,37,9/8/2025,Gandaki,6.0,Kaski,Pokhara Metropolitan City,Charak1 hos,9/8/2025
4,5,Dengue,Male,40,9/8/2025,Gandaki,6.0,Kaski,Pokhara Metropolitan City,Charak1 hos,9/8/2025
...,...,...,...,...,...,...,...,...,...,...,...
5926,5927,Dengue,Female,42,7/19/2023,Gandaki,30.0,Kaski,Pokhara Metropolitan City,ICDH Hospital,7/19/2023
5927,5928,Dengue,Female,16,7/19/2023,Gandaki,30.0,Kaski,Pokhara Metropolitan City,ICDH Hospital,7/19/2023
5928,5929,Dengue,Female,19,7/16/2023,Gandaki,30.0,Kaski,Pokhara Metropolitan City,ICDH Hospital,7/16/2023
5929,5930,Dengue,Female,38,7/16/2023,Gandaki,30.0,Kaski,Pokhara Metropolitan City,ICDH Hospital,7/16/2023
5930,5931,Dengue,Male,40,6/21/2023,Gandaki,31.0,Kaski,Pokhara Metropolitan City,ICDH Hospital,6/27/2023

In [4]:
duplicate_count = df.duplicated().sum()
print(f"Total duplicate rows: {duplicate_count}")

Total duplicate rows: 0

In [5]:
df['Responsible ward no'].isna().sum()  # check how many are missing

553

In [6]:
df['Date of Registration (M/d/yyyy)'].isna().sum()  # check how many are missing

0

In [7]:
df['Responsible municipality'].isna().sum()  # check how many are missing

60

In [8]:
df['Responsible district'] = df['Responsible district'].str.strip().str.lower()
df = df[df['Responsible district'] == 'kaski']

In [9]:
print(df['Responsible district'].unique())
print("Remaining rows:", len(df))

['kaski']
Remaining rows: 5912

In [10]:
df.loc[df['Responsible ward no'] > 12, 'Responsible municipality'] = 'Pokhara Metropolitan City'

In [11]:
print(df[['Responsible ward no', 'Responsible municipality']].head(20))

    Responsible ward no   Responsible municipality
0                  10.0                        NaN
1                   8.0  Pokhara Metropolitan City
2                   NaN  Pokhara Metropolitan City
3                   6.0  Pokhara Metropolitan City
4                   6.0  Pokhara Metropolitan City
5                   8.0  Pokhara Metropolitan City
6                  30.0  Pokhara Metropolitan City
7                  33.0  Pokhara Metropolitan City
8                   6.0  Pokhara Metropolitan City
9                  12.0  Pokhara Metropolitan City
10                 10.0  Pokhara Metropolitan City
11                 30.0  Pokhara Metropolitan City
12                 30.0  Pokhara Metropolitan City
13                  NaN  Pokhara Metropolitan City
15                  6.0  Pokhara Metropolitan City
17                 17.0  Pokhara Metropolitan City
18                 17.0  Pokhara Metropolitan City
19                 17.0  Pokhara Metropolitan City
20                  8.0  Pokhara Metropolitan City
21                  8.0  Pokhara Metropolitan City

In [12]:
df2 = pd.read_csv(r"C:\Users\dhrub\Desktop\Dengue_summary_report\Events 2025.csv")

In [13]:
df2

,Event,Program stage,Event date,Longitude,Latitude,Organisation unit name,Organisation unit code,Organisation unit,Disease Name,Diagnosis,District,Ward Number,Municipality
0,V2CP7Jr3CPM,uTJBFFVYXqA,2019-08-02 00:00:00.0,0,0,POKHARA ACADEMY OF HEALTH SCIENCES_KASKI,NaN,E7KRzq0nI80,Dengue,Confirm,405 KASKI,8.0,40504
1,Piaxzx9X1YU,uTJBFFVYXqA,2019-08-02 00:00:00.0,0,0,POKHARA ACADEMY OF HEALTH SCIENCES_KASKI,NaN,E7KRzq0nI80,Dengue,Confirm,405 KASKI,8.0,40504
2,Fxoec3GTznW,uTJBFFVYXqA,2019-08-02 00:00:00.0,0,0,POKHARA ACADEMY OF HEALTH SCIENCES_KASKI,NaN,E7KRzq0nI80,Dengue,Confirm,405 KASKI,9.0,40504
3,nuUb4oehavR,uTJBFFVYXqA,2019-08-02 00:00:00.0,0,0,POKHARA ACADEMY OF HEALTH SCIENCES_KASKI,NaN,E7KRzq0nI80,Dengue,Confirm,405 KASKI,8.0,40504
4,ALqE9BHNtFV,uTJBFFVYXqA,2019-08-03 00:00:00.0,0,0,POKHARA ACADEMY OF HEALTH SCIENCES_KASKI,NaN,E7KRzq0nI80,Dengue,Confirm,405 KASKI,8.0,40504
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7910,X9PnWOGtCV8,uTJBFFVYXqA,2025-06-01 00:00:00.0,0,0,POKHARA ACADEMY OF HEALTH SCIENCES_KASKI,NaN,E7KRzq0nI80,Dengue,Confirm,405 KASKI,NaN,40504 Pokhara Lekhnath Metropolitan City
7911,AEkQvzfjnHr,uTJBFFVYXqA,2025-08-14 00:00:00.0,0,0,MANIPAL TEACHING HOSPITAL_KASKI,NaN,vqi6uD883rm,Dengue,Confirm,405 KASKI,11.0,40504 Pokhara Lekhnath Metropolitan City
7912,y8GFvIyMyGQ,uTJBFFVYXqA,2025-01-15 00:00:00.0,0,0,MANIPAL TEACHING HOSPITAL_KASKI,NaN,vqi6uD883rm,Dengue,Confirm,405 KASKI,17.0,40504 Pokhara Lekhnath Metropolitan City
7913,cl9Jh7z5f2o,uTJBFFVYXqA,2025-09-14 00:00:00.0,0,0,POKHARA ACADEMY OF HEALTH SCIENCES_KASKI,NaN,E7KRzq0nI80,Dengue,Confirm,405 KASKI,NaN,NaN
7914,Ekbqw0gQvBF,uTJBFFVYXqA,2025-01-23 00:00:00.0,0,0,MANIPAL TEACHING HOSPITAL_KASKI,NaN,vqi6uD883rm,Dengue,Confirm,405 KASKI,11.0,40504 Pokhara Lekhnath Metropolitan City

In [14]:
duplicate_count2 = df2.duplicated().sum()
print(f"Total duplicate rows: {duplicate_count2}")

Total duplicate rows: 0

In [15]:
columns_to_remove = ['Event', 'Program stage', 'Longitude', 'Latitude', 'Organisation unit code', 'Organisation unit', 'Diagnosis']
df2 = df2.drop(columns=columns_to_remove)

In [16]:
df

,S.N,Disease,Sex,Age,Date of Registration (M/d/yyyy),Responsible province,Responsible ward no,Responsible district,Responsible municipality,Reporting user,Creation date (M/d/yyyy)
0,1,Dengue,Female,56,9/18/2025,Gandaki,10.0,kaski,NaN,Regional1 hos,9/19/2025
1,2,Dengue,Female,75,9/10/2025,Gandaki,8.0,kaski,Pokhara Metropolitan City,Metrocity1 hos,9/16/2025
2,3,Dengue,Female,43,9/13/2025,Gandaki,NaN,kaski,Pokhara Metropolitan City,Regional1 hos,9/14/2025
3,4,Dengue,Female,37,9/8/2025,Gandaki,6.0,kaski,Pokhara Metropolitan City,Charak1 hos,9/8/2025
4,5,Dengue,Male,40,9/8/2025,Gandaki,6.0,kaski,Pokhara Metropolitan City,Charak1 hos,9/8/2025
...,...,...,...,...,...,...,...,...,...,...,...
5926,5927,Dengue,Female,42,7/19/2023,Gandaki,30.0,kaski,Pokhara Metropolitan City,ICDH Hospital,7/19/2023
5927,5928,Dengue,Female,16,7/19/2023,Gandaki,30.0,kaski,Pokhara Metropolitan City,ICDH Hospital,7/19/2023
5928,5929,Dengue,Female,19,7/16/2023,Gandaki,30.0,kaski,Pokhara Metropolitan City,ICDH Hospital,7/16/2023
5929,5930,Dengue,Female,38,7/16/2023,Gandaki,30.0,kaski,Pokhara Metropolitan City,ICDH Hospital,7/16/2023
5930,5931,Dengue,Male,40,6/21/2023,Gandaki,31.0,kaski,Pokhara Metropolitan City,ICDH Hospital,6/27/2023

In [17]:
df = df.drop(columns=['Creation date (M/d/yyyy)'])

In [18]:
df

,S.N,Disease,Sex,Age,Date of Registration (M/d/yyyy),Responsible province,Responsible ward no,Responsible district,Responsible municipality,Reporting user
0,1,Dengue,Female,56,9/18/2025,Gandaki,10.0,kaski,NaN,Regional1 hos
1,2,Dengue,Female,75,9/10/2025,Gandaki,8.0,kaski,Pokhara Metropolitan City,Metrocity1 hos
2,3,Dengue,Female,43,9/13/2025,Gandaki,NaN,kaski,Pokhara Metropolitan City,Regional1 hos
3,4,Dengue,Female,37,9/8/2025,Gandaki,6.0,kaski,Pokhara Metropolitan City,Charak1 hos
4,5,Dengue,Male,40,9/8/2025,Gandaki,6.0,kaski,Pokhara Metropolitan City,Charak1 hos
...,...,...,...,...,...,...,...,...,...,...
5926,5927,Dengue,Female,42,7/19/2023,Gandaki,30.0,kaski,Pokhara Metropolitan City,ICDH Hospital
5927,5928,Dengue,Female,16,7/19/2023,Gandaki,30.0,kaski,Pokhara Metropolitan City,ICDH Hospital
5928,5929,Dengue,Female,19,7/16/2023,Gandaki,30.0,kaski,Pokhara Metropolitan City,ICDH Hospital
5929,5930,Dengue,Female,38,7/16/2023,Gandaki,30.0,kaski,Pokhara Metropolitan City,ICDH Hospital
5930,5931,Dengue,Male,40,6/21/2023,Gandaki,31.0,kaski,Pokhara Metropolitan City,ICDH Hospital

In [19]:
df2

,Event date,Organisation unit name,Disease Name,District,Ward Number,Municipality
0,2019-08-02 00:00:00.0,POKHARA ACADEMY OF HEALTH SCIENCES_KASKI,Dengue,405 KASKI,8.0,40504
1,2019-08-02 00:00:00.0,POKHARA ACADEMY OF HEALTH SCIENCES_KASKI,Dengue,405 KASKI,8.0,40504
2,2019-08-02 00:00:00.0,POKHARA ACADEMY OF HEALTH SCIENCES_KASKI,Dengue,405 KASKI,9.0,40504
3,2019-08-02 00:00:00.0,POKHARA ACADEMY OF HEALTH SCIENCES_KASKI,Dengue,405 KASKI,8.0,40504
4,2019-08-03 00:00:00.0,POKHARA ACADEMY OF HEALTH SCIENCES_KASKI,Dengue,405 KASKI,8.0,40504
...,...,...,...,...,...,...
7910,2025-06-01 00:00:00.0,POKHARA ACADEMY OF HEALTH SCIENCES_KASKI,Dengue,405 KASKI,NaN,40504 Pokhara Lekhnath Metropolitan City
7911,2025-08-14 00:00:00.0,MANIPAL TEACHING HOSPITAL_KASKI,Dengue,405 KASKI,11.0,40504 Pokhara Lekhnath Metropolitan City
7912,2025-01-15 00:00:00.0,MANIPAL TEACHING HOSPITAL_KASKI,Dengue,405 KASKI,17.0,40504 Pokhara Lekhnath Metropolitan City
7913,2025-09-14 00:00:00.0,POKHARA ACADEMY OF HEALTH SCIENCES_KASKI,Dengue,405 KASKI,NaN,NaN
7914,2025-01-23 00:00:00.0,MANIPAL TEACHING HOSPITAL_KASKI,Dengue,405 KASKI,11.0,40504 Pokhara Lekhnath Metropolitan City

In [20]:
column_to_clean = 'Event date'
df2[column_to_clean] = pd.to_datetime(df2[column_to_clean])
df2[column_to_clean] = df2[column_to_clean].dt.normalize()

In [21]:
df2

,Event date,Organisation unit name,Disease Name,District,Ward Number,Municipality
0,2019-08-02,POKHARA ACADEMY OF HEALTH SCIENCES_KASKI,Dengue,405 KASKI,8.0,40504
1,2019-08-02,POKHARA ACADEMY OF HEALTH SCIENCES_KASKI,Dengue,405 KASKI,8.0,40504
2,2019-08-02,POKHARA ACADEMY OF HEALTH SCIENCES_KASKI,Dengue,405 KASKI,9.0,40504
3,2019-08-02,POKHARA ACADEMY OF HEALTH SCIENCES_KASKI,Dengue,405 KASKI,8.0,40504
4,2019-08-03,POKHARA ACADEMY OF HEALTH SCIENCES_KASKI,Dengue,405 KASKI,8.0,40504
...,...,...,...,...,...,...
7910,2025-06-01,POKHARA ACADEMY OF HEALTH SCIENCES_KASKI,Dengue,405 KASKI,NaN,40504 Pokhara Lekhnath Metropolitan City
7911,2025-08-14,MANIPAL TEACHING HOSPITAL_KASKI,Dengue,405 KASKI,11.0,40504 Pokhara Lekhnath Metropolitan City
7912,2025-01-15,MANIPAL TEACHING HOSPITAL_KASKI,Dengue,405 KASKI,17.0,40504 Pokhara Lekhnath Metropolitan City
7913,2025-09-14,POKHARA ACADEMY OF HEALTH SCIENCES_KASKI,Dengue,405 KASKI,NaN,NaN
7914,2025-01-23,MANIPAL TEACHING HOSPITAL_KASKI,Dengue,405 KASKI,11.0,40504 Pokhara Lekhnath Metropolitan City

In [22]:
df = df.drop(columns=['Sex', 'Age', 'Responsible province'])

In [23]:
df

,S.N,Disease,Date of Registration (M/d/yyyy),Responsible ward no,Responsible district,Responsible municipality,Reporting user
0,1,Dengue,9/18/2025,10.0,kaski,NaN,Regional1 hos
1,2,Dengue,9/10/2025,8.0,kaski,Pokhara Metropolitan City,Metrocity1 hos
2,3,Dengue,9/13/2025,NaN,kaski,Pokhara Metropolitan City,Regional1 hos
3,4,Dengue,9/8/2025,6.0,kaski,Pokhara Metropolitan City,Charak1 hos
4,5,Dengue,9/8/2025,6.0,kaski,Pokhara Metropolitan City,Charak1 hos
...,...,...,...,...,...,...,...
5926,5927,Dengue,7/19/2023,30.0,kaski,Pokhara Metropolitan City,ICDH Hospital
5927,5928,Dengue,7/19/2023,30.0,kaski,Pokhara Metropolitan City,ICDH Hospital
5928,5929,Dengue,7/16/2023,30.0,kaski,Pokhara Metropolitan City,ICDH Hospital
5929,5930,Dengue,7/16/2023,30.0,kaski,Pokhara Metropolitan City,ICDH Hospital
5930,5931,Dengue,6/21/2023,31.0,kaski,Pokhara Metropolitan City,ICDH Hospital

In [24]:
df.rename(columns={
    'Date of Registration (M/d/yyyy)': 'Event date',
    'Responsible ward no': 'Ward Number',
    'Responsible district': 'District',
    'Responsible municipality': 'Municipality',
    'Reporting user': 'Hospital'
}, inplace=True)

In [25]:
df2.rename(columns={
    'Organisation unit name': 'Hospital'
}, inplace=True)

In [26]:
df

,S.N,Disease,Event date,Ward Number,District,Municipality,Hospital
0,1,Dengue,9/18/2025,10.0,kaski,NaN,Regional1 hos
1,2,Dengue,9/10/2025,8.0,kaski,Pokhara Metropolitan City,Metrocity1 hos
2,3,Dengue,9/13/2025,NaN,kaski,Pokhara Metropolitan City,Regional1 hos
3,4,Dengue,9/8/2025,6.0,kaski,Pokhara Metropolitan City,Charak1 hos
4,5,Dengue,9/8/2025,6.0,kaski,Pokhara Metropolitan City,Charak1 hos
...,...,...,...,...,...,...,...
5926,5927,Dengue,7/19/2023,30.0,kaski,Pokhara Metropolitan City,ICDH Hospital
5927,5928,Dengue,7/19/2023,30.0,kaski,Pokhara Metropolitan City,ICDH Hospital
5928,5929,Dengue,7/16/2023,30.0,kaski,Pokhara Metropolitan City,ICDH Hospital
5929,5930,Dengue,7/16/2023,30.0,kaski,Pokhara Metropolitan City,ICDH Hospital
5930,5931,Dengue,6/21/2023,31.0,kaski,Pokhara Metropolitan City,ICDH Hospital

In [27]:
df2

,Event date,Hospital,Disease Name,District,Ward Number,Municipality
0,2019-08-02,POKHARA ACADEMY OF HEALTH SCIENCES_KASKI,Dengue,405 KASKI,8.0,40504
1,2019-08-02,POKHARA ACADEMY OF HEALTH SCIENCES_KASKI,Dengue,405 KASKI,8.0,40504
2,2019-08-02,POKHARA ACADEMY OF HEALTH SCIENCES_KASKI,Dengue,405 KASKI,9.0,40504
3,2019-08-02,POKHARA ACADEMY OF HEALTH SCIENCES_KASKI,Dengue,405 KASKI,8.0,40504
4,2019-08-03,POKHARA ACADEMY OF HEALTH SCIENCES_KASKI,Dengue,405 KASKI,8.0,40504
...,...,...,...,...,...,...
7910,2025-06-01,POKHARA ACADEMY OF HEALTH SCIENCES_KASKI,Dengue,405 KASKI,NaN,40504 Pokhara Lekhnath Metropolitan City
7911,2025-08-14,MANIPAL TEACHING HOSPITAL_KASKI,Dengue,405 KASKI,11.0,40504 Pokhara Lekhnath Metropolitan City
7912,2025-01-15,MANIPAL TEACHING HOSPITAL_KASKI,Dengue,405 KASKI,17.0,40504 Pokhara Lekhnath Metropolitan City
7913,2025-09-14,POKHARA ACADEMY OF HEALTH SCIENCES_KASKI,Dengue,405 KASKI,NaN,NaN
7914,2025-01-23,MANIPAL TEACHING HOSPITAL_KASKI,Dengue,405 KASKI,11.0,40504 Pokhara Lekhnath Metropolitan City

In [28]:
df=df.drop(columns=['S.N'])

In [29]:
df

,Disease,Event date,Ward Number,District,Municipality,Hospital
0,Dengue,9/18/2025,10.0,kaski,NaN,Regional1 hos
1,Dengue,9/10/2025,8.0,kaski,Pokhara Metropolitan City,Metrocity1 hos
2,Dengue,9/13/2025,NaN,kaski,Pokhara Metropolitan City,Regional1 hos
3,Dengue,9/8/2025,6.0,kaski,Pokhara Metropolitan City,Charak1 hos
4,Dengue,9/8/2025,6.0,kaski,Pokhara Metropolitan City,Charak1 hos
...,...,...,...,...,...,...
5926,Dengue,7/19/2023,30.0,kaski,Pokhara Metropolitan City,ICDH Hospital
5927,Dengue,7/19/2023,30.0,kaski,Pokhara Metropolitan City,ICDH Hospital
5928,Dengue,7/16/2023,30.0,kaski,Pokhara Metropolitan City,ICDH Hospital
5929,Dengue,7/16/2023,30.0,kaski,Pokhara Metropolitan City,ICDH Hospital
5930,Dengue,6/21/2023,31.0,kaski,Pokhara Metropolitan City,ICDH Hospital

In [30]:
merged_df = pd.concat([df, df2], ignore_index=True)

In [31]:
merged_df

,Disease,Event date,Ward Number,District,Municipality,Hospital,Disease Name
0,Dengue,9/18/2025,10.0,kaski,NaN,Regional1 hos,NaN
1,Dengue,9/10/2025,8.0,kaski,Pokhara Metropolitan City,Metrocity1 hos,NaN
2,Dengue,9/13/2025,NaN,kaski,Pokhara Metropolitan City,Regional1 hos,NaN
3,Dengue,9/8/2025,6.0,kaski,Pokhara Metropolitan City,Charak1 hos,NaN
4,Dengue,9/8/2025,6.0,kaski,Pokhara Metropolitan City,Charak1 hos,NaN
...,...,...,...,...,...,...,...
13822,NaN,2025-06-01 00:00:00,NaN,405 KASKI,40504 Pokhara Lekhnath Metropolitan City,POKHARA ACADEMY OF HEALTH SCIENCES_KASKI,Dengue
13823,NaN,2025-08-14 00:00:00,11.0,405 KASKI,40504 Pokhara Lekhnath Metropolitan City,MANIPAL TEACHING HOSPITAL_KASKI,Dengue
13824,NaN,2025-01-15 00:00:00,17.0,405 KASKI,40504 Pokhara Lekhnath Metropolitan City,MANIPAL TEACHING HOSPITAL_KASKI,Dengue
13825,NaN,2025-09-14 00:00:00,NaN,405 KASKI,NaN,POKHARA ACADEMY OF HEALTH SCIENCES_KASKI,Dengue
13826,NaN,2025-01-23 00:00:00,11.0,405 KASKI,40504 Pokhara Lekhnath Metropolitan City,MANIPAL TEACHING HOSPITAL_KASKI,Dengue

In [32]:
merged_df['Municipality'] = merged_df['Municipality'].str.strip().str.title()
merged_df['Municipality'] = merged_df['Municipality'].replace('40504 Pokhara Lekhnath Metropolitan City', 'Pokhara Metropolitan City')

In [33]:
merged_df

,Disease,Event date,Ward Number,District,Municipality,Hospital,Disease Name
0,Dengue,9/18/2025,10.0,kaski,NaN,Regional1 hos,NaN
1,Dengue,9/10/2025,8.0,kaski,Pokhara Metropolitan City,Metrocity1 hos,NaN
2,Dengue,9/13/2025,NaN,kaski,Pokhara Metropolitan City,Regional1 hos,NaN
3,Dengue,9/8/2025,6.0,kaski,Pokhara Metropolitan City,Charak1 hos,NaN
4,Dengue,9/8/2025,6.0,kaski,Pokhara Metropolitan City,Charak1 hos,NaN
...,...,...,...,...,...,...,...
13822,NaN,2025-06-01 00:00:00,NaN,405 KASKI,Pokhara Metropolitan City,POKHARA ACADEMY OF HEALTH SCIENCES_KASKI,Dengue
13823,NaN,2025-08-14 00:00:00,11.0,405 KASKI,Pokhara Metropolitan City,MANIPAL TEACHING HOSPITAL_KASKI,Dengue
13824,NaN,2025-01-15 00:00:00,17.0,405 KASKI,Pokhara Metropolitan City,MANIPAL TEACHING HOSPITAL_KASKI,Dengue
13825,NaN,2025-09-14 00:00:00,NaN,405 KASKI,NaN,POKHARA ACADEMY OF HEALTH SCIENCES_KASKI,Dengue
13826,NaN,2025-01-23 00:00:00,11.0,405 KASKI,Pokhara Metropolitan City,MANIPAL TEACHING HOSPITAL_KASKI,Dengue

In [34]:
merged_df['District'] = merged_df['District'].str.strip().str.title()
merged_df['District'] = merged_df['District'].replace('405 Kaski', 'kaski')

In [35]:
merged_df['Ward Number'].isna().sum() # check how many are missing

4023

In [36]:
merged_df['Municipality'].isna().sum() # check how many are missing

1849

In [37]:
merged_df['Municipality' and 'Ward Number'].isna().sum() # check how many are missing

4023

In [38]:
merged_df.loc[merged_df['Ward Number'] > 12, 'Municipality'] = 'Pokhara Metropolitan City'

In [39]:
merged_df

,Disease,Event date,Ward Number,District,Municipality,Hospital,Disease Name
0,Dengue,9/18/2025,10.0,Kaski,NaN,Regional1 hos,NaN
1,Dengue,9/10/2025,8.0,Kaski,Pokhara Metropolitan City,Metrocity1 hos,NaN
2,Dengue,9/13/2025,NaN,Kaski,Pokhara Metropolitan City,Regional1 hos,NaN
3,Dengue,9/8/2025,6.0,Kaski,Pokhara Metropolitan City,Charak1 hos,NaN
4,Dengue,9/8/2025,6.0,Kaski,Pokhara Metropolitan City,Charak1 hos,NaN
...,...,...,...,...,...,...,...
13822,NaN,2025-06-01 00:00:00,NaN,kaski,Pokhara Metropolitan City,POKHARA ACADEMY OF HEALTH SCIENCES_KASKI,Dengue
13823,NaN,2025-08-14 00:00:00,11.0,kaski,Pokhara Metropolitan City,MANIPAL TEACHING HOSPITAL_KASKI,Dengue
13824,NaN,2025-01-15 00:00:00,17.0,kaski,Pokhara Metropolitan City,MANIPAL TEACHING HOSPITAL_KASKI,Dengue
13825,NaN,2025-09-14 00:00:00,NaN,kaski,NaN,POKHARA ACADEMY OF HEALTH SCIENCES_KASKI,Dengue
13826,NaN,2025-01-23 00:00:00,11.0,kaski,Pokhara Metropolitan City,MANIPAL TEACHING HOSPITAL_KASKI,Dengue

In [40]:
merged_df['Municipality'] = merged_df['Municipality'].str.strip().str.title()				
merged_df['Municipality'] = merged_df['Municipality'].replace('40502 Machhapuchchhre Rural Municipality', 'Machhapuchchhre Rural Municipality')

In [41]:
merged_df['Municipality'] = merged_df['Municipality'].str.strip().str.title()
merged_df['Municipality'] = merged_df['Municipality'].replace('40503 Annapurna Rural Municipality', 'Annapurna Rural Municipality')

In [42]:
merged_df['Municipality'] = merged_df['Municipality'].str.strip().str.title()
merged_df['Municipality'] = merged_df['Municipality'].replace('Annapurna Rural Municipality_Kaski', 'Annapurna Rural Municipality')

In [43]:
merged_df['Municipality'] = merged_df['Municipality'].str.strip().str.title()
merged_df['Municipality'] = merged_df['Municipality'].replace('40505 Rupa Rural Municipality', 'Rupa Rural Municipality')

In [44]:
merged_df['Municipality'] = merged_df['Municipality'].str.strip().str.title()
merged_df['Municipality'] = merged_df['Municipality'].replace('40501 Madi Rural Municipality', 'Madi Rural Municipality')

In [45]:
merged_df.head(10)

,Disease,Event date,Ward Number,District,Municipality,Hospital,Disease Name
0,Dengue,9/18/2025,10.0,Kaski,NaN,Regional1 hos,NaN
1,Dengue,9/10/2025,8.0,Kaski,Pokhara Metropolitan City,Metrocity1 hos,NaN
2,Dengue,9/13/2025,NaN,Kaski,Pokhara Metropolitan City,Regional1 hos,NaN
3,Dengue,9/8/2025,6.0,Kaski,Pokhara Metropolitan City,Charak1 hos,NaN
4,Dengue,9/8/2025,6.0,Kaski,Pokhara Metropolitan City,Charak1 hos,NaN
5,Dengue,9/4/2025,8.0,Kaski,Pokhara Metropolitan City,Charak1 hos,NaN
6,Dengue,9/2/2025,30.0,Kaski,Pokhara Metropolitan City,ICDH Hospital,NaN
7,Dengue,9/3/2025,33.0,Kaski,Pokhara Metropolitan City,GP Koirala Hospital,NaN
8,Dengue,7/20/2025,6.0,Kaski,Pokhara Metropolitan City,MediPlus_hosp hos,NaN
9,Dengue,7/25/2025,12.0,Kaski,Pokhara Metropolitan City,MediPlus_hosp hos,NaN

In [46]:
merged_df = merged_df.drop(['Disease', 'Hospital', 'Disease Name'], axis=1)

In [47]:
merged_df.head(10)

  Event date  Ward Number District               Municipality
0  9/18/2025         10.0    Kaski                        NaN
1  9/10/2025          8.0    Kaski  Pokhara Metropolitan City
2  9/13/2025          NaN    Kaski  Pokhara Metropolitan City
3   9/8/2025          6.0    Kaski  Pokhara Metropolitan City
4   9/8/2025          6.0    Kaski  Pokhara Metropolitan City
5   9/4/2025          8.0    Kaski  Pokhara Metropolitan City
6   9/2/2025         30.0    Kaski  Pokhara Metropolitan City
7   9/3/2025         33.0    Kaski  Pokhara Metropolitan City
8  7/20/2025          6.0    Kaski  Pokhara Metropolitan City
9  7/25/2025         12.0    Kaski  Pokhara Metropolitan City

In [48]:
merged_df['Municipality'] = (
    merged_df['Municipality']
    .str.strip()
    .replace({'Pokhara Metropolitan City': 'Pokhara'})
)

In [49]:
merged_df = merged_df.copy()
merged_df['Event date'] = pd.to_datetime(merged_df['Event date'], format='mixed', errors='coerce')
merged_df['year'] = merged_df['Event date'].dt.year
merged_df['month'] = merged_df['Event date'].dt.month

In [50]:
merged_df['Event date'].dtype

dtype('<M8[ns]')

In [51]:
merged_df['Event date'] = pd.to_datetime(merged_df['Event date'])
merged_df['year'] = merged_df['Event date'].dt.year
merged_df['month'] = merged_df['Event date'].dt.month

In [52]:
# Save to Excel
merged_df.to_csv(r"C:\Users\dhrub\Desktop\Dengue_summary_report\merged_output1.csv", index=False)